# Generated by Django 3.2.16 on 2022-11-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.TextField()),
                ('result_id', models.CharField(max_length=100, null=True)),
                ('case_name', models.CharField(max_length=50, null=True)),
                ('end_status', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'job_results',
            },
        ),
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(db_column='name', max_length=50)),
                ('case_code', models.TextField(db_column='code')),
                ('run_status', models.BooleanField(default=False)),
                ('create_user', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('suit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.casesuit')),
            ],
        ),
    ]
