# Generated by Django 3.2 on 2022-08-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(db_column='name', max_length=50)),
                ('case_code', models.TextField(db_column='code')),
                ('run_status', models.BooleanField(default=False)),
                ('create_user', models.CharField(max_length=50)),
            ],
        ),
    ]
