# Generated by Django 3.2 on 2022-08-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_apicase'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
