# Generated by Django 3.2 on 2022-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_jobresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='case_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
